-- N/OPS — ajout des questionnaires par poste
-- Ce script conserve les questions et les résultats existants.
-- Les 100 nouvelles questions sont publiées mais doivent être relues par le référent
-- HSE / exploitation avant un usage d'habilitation ou de validation d'aptitude.

begin;

alter table public.questions add column if not exists target_posts jsonb not null default '[]'::jsonb;
alter table public.attempts add column if not exists post_profile_id text not null default 'operateur';

-- Cible les 200 questions historiques sur les postes concernés lorsque le champ est vide.
update public.questions
set target_posts = case
  when theme_id = 'securite' then '["operateur", "rondier", "chef-thermique", "chef-elec", "chef-quart"]'::jsonb
  when theme_id in ('gaz', 'hydrogene', 'torche', 'hp-bp', 'rechauffeurs') then '["operateur", "rondier", "chef-thermique", "chef-quart"]'::jsonb
  else '["operateur", "rondier", "chef-thermique", "chef-elec", "chef-quart"]'::jsonb
end
where target_posts = '[]'::jsonb;

insert into public.questions (
  id, theme_id, status, critical, prompt, choices, correct_index, rationale, source, target_posts
) values
('NC-OP-001', 'securite', 'published', true, 'Face a un conflit entre production et securite, quel principe FAF s applique ?', '["La production prime si le retard est important","La decision est reportee a la releve","La manœuvre est realisee sans information","La securite prime sur la production"]'::jsonb, 3, 'La charte FAF rappelle que la securite des personnes et des installations prime sur la production.', 'FAF-REF-001', '["operateur"]'::jsonb),
('NC-OP-002', 'securite', 'published', true, 'Vous constatez une anomalie HSEEQ sur une installation exterieure. Quel reflexe est attendu ?', '["La corriger sans rendre compte","La transmettre uniquement a la releve","Avertir le chef de quart et la tracer selon le processus en vigueur","Attendre que l anomalie disparaisse"]'::jsonb, 2, 'La definition de fonction demande de signaler les anomalies et d en informer le chef de quart.', 'DRH-DEF-LPU-021', '["operateur"]'::jsonb),
('NC-OP-003', 'securite', 'published', true, 'A mi-poste, quelle action de surveillance est prevue pour l operateur exterieur 3x8 ?', '["Arreter le reseau gaz","Realiser une ronde de securite des zones sensibles de la Centrale","Acquitter toutes les alarmes de la salle de controle","Modifier les seuils des protections"]'::jsonb, 1, 'La ronde de securite porte notamment sur le F213, le F113, les surchauffeurs, les chaudieres et les combustibles.', 'DRH-DEF-LPU-021', '["operateur"]'::jsonb),
('NC-OP-004', 'securite', 'published', false, 'Sur quel support les parametres operatoires releves pendant une ronde doivent-ils etre consignes ?', '["La feuille de releve EXP-U-00-006","Un post-it sans date","Le registre des permis electriques uniquement","Aucun support si la valeur est normale"]'::jsonb, 0, 'La fonction d operateur exterieur 3x8 cite la feuille de releve EXP-U-00-006.', 'DRH-DEF-LPU-021', '["operateur"]'::jsonb),
('NC-OP-005', 'securite', 'published', true, 'Lors d une mise a disposition pour travaux, quelle verification terrain est indispensable avant validation ?', '["Demarrer l equipement pour confirmer sa disponibilite","Supprimer les scelles pour gagner du temps","Laisser la verification a l entreprise intervenante","Verifier le zero-energie et les isolements necessaires"]'::jsonb, 3, 'L operateur effectue les controles necessaires au zero-energie et participe a la pose et au suivi des scelles.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-006', 'securite', 'published', true, 'Qui donne l autorite pour arreter ou remettre en service un appareil dans la mission de l operateur 2x8 ?', '["Le laboratoire","Le fournisseur de gaz","Le chef de quart, avec l aide de l operateur 3x8","L operateur seul sans communication"]'::jsonb, 2, 'La definition de fonction place ces manœuvres sous l autorite du chef de quart.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-007', 'securite', 'published', false, 'A la fin des travaux, que doit faire l operateur avant la remise en service ?', '["Effacer le permis de travail","Recevoir la fin des travaux, controler la zone et participer a la remise en service autorisee","Remettre l energie avant l evacuation du personnel","Retirer seul toutes les protections"]'::jsonb, 1, 'La reception de fin de travaux et la remise en service sont realisees dans le cadre defini par la hierarchie.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-008', 'gaz', 'published', true, 'La temperature de sortie du F213 baisse. Quel premier ensemble de controles est coherent avec EXP-U-15-006 ?', '["Verifier E004/E005, le niveau local, le tracage et les sources de condensation","Ouvrir toutes les purges sans verifier les isolements","Arreter la ventilation et attendre","Modifier les protections de la chaudiere"]'::jsonb, 0, 'La consigne demande de verifier les rechauffeurs, la vaporisation, le niveau, le tracage et les condensats avant action.', 'EXP-U-15-006', '["operateur"]'::jsonb),
('NC-OP-009', 'gaz', 'published', true, 'Avant une purge du F213, quelle precaution particuliere est explicitement mentionnee ?', '["Purger a l air libre sans controle","Retirer la platine sans autorisation","Utiliser un multimètre","Verifier l isolement des vannes d encadrement et intervenir sous ARI selon la consigne"]'::jsonb, 3, 'La purge normalement platinee du F213 est encadree par la verification des vannes et le port de l ARI.', 'EXP-U-15-006', '["operateur"]'::jsonb),
('NC-OP-010', 'gaz', 'published', false, 'Lors d une reprise de gaz acetyléniques sur les surchauffeurs, quel point doit etre surveille ?', '["La puissance reactive du RDE","Le niveau du chateau d eau uniquement","Le niveau du F113 et la presence eventuelle de condensats","Le niveau d eau potable du site"]'::jsonb, 2, 'EXP-U-15-006 demande de surveiller le F113 et de le purger en presence de condensats.', 'EXP-U-15-006', '["operateur"]'::jsonb),
('NC-OP-011', 'torche', 'published', false, 'A quelle frequence la ronde au F113 est-elle prevue dans la consigne de brulage des gaz residuaires ?', '["Uniquement sur alarme","Une fois par poste","Une fois par mois","Une fois par an"]'::jsonb, 1, 'La surveillance du reseau residuaire comprend une ronde au F113 par poste.', 'EXP-U-15-01', '["operateur"]'::jsonb),
('NC-OP-012', 'torche', 'published', false, 'Quand le nettoyage des lancettes de butadiene est-il planifie ?', '["Chaque jeudi avec le cadre documentaire prevu","A chaque changement de quart sans permis","Uniquement apres un incendie","Tous les cinq ans"]'::jsonb, 0, 'La consigne prevoit un nettoyage hebdomadaire le jeudi, avec permis annuel et DAP.', 'EXP-U-15-01', '["operateur"]'::jsonb),
('NC-OP-013', 'torche', 'published', true, 'Quelle attitude adopter si une fuite, une vibration ou un echauffement anormal est observe ?', '["Continuer la ronde sans le noter","Augmenter la charge de l equipement","Neutraliser l alarme sans diagnostic","Signaler l ecart au chef de quart et appliquer la mise en securite definie"]'::jsonb, 3, 'La fonction demande de surveiller ces ecarts, de les signaler et de realiser les isolements necessaires.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-014', 'securite', 'published', true, 'Quel equipement de detection est explicitement cite dans le profil de l operateur exterieur ?', '["Un analyseur reseau HT uniquement","Une caméra de surveillance fixe","Un detecteur CO et un explosimetre","Un thermometre medical uniquement"]'::jsonb, 2, 'Le profil de fonction mentionne la connaissance et l utilisation du detecteur CO et de l explosimetre.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-015', 'securite', 'published', false, 'Lors d une manœuvre terrain, que faut-il faire si les conditions de securite ne sont pas reunies ?', '["Supprimer la protection qui gene","Arreter ou suspendre l action et en informer la hierarchie","Poursuivre pour ne pas retarder la production","Deleguer a une personne non habilitee"]'::jsonb, 1, 'La culture FAF et les definitions de fonction imposent la priorite a la securite et la remontée des ecarts.', 'FAF-REF-001', '["operateur"]'::jsonb),
('NC-OP-016', 'rechauffeurs', 'published', false, 'Quelle activite fait partie de la topo-maintenance 2x8 dans le perimetre defini ?', '["Remplacer un manometre dans la limite prevue par la consigne","Modifier un relais HT sous tension","Changer un reglage de protection RDE","Depanner un transformateur 63 kV"]'::jsonb, 0, 'La liste de topo-maintenance cite notamment le remplacement de manometres dans les limites definies.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-017', 'rechauffeurs', 'published', false, 'Pourquoi la verification des bruleurs est-elle realisee avec un deuxieme operateur lorsqu il est present ?', '["Pour eviter toute trace dans le cahier de quart","Pour supprimer le besoin d EPI","Pour modifier la consigne sans validation","Pour beneficier d une presence a deux lors de l entretien des bruleurs"]'::jsonb, 3, 'La definition de fonction precise que l entretien des bruleurs est realise avec le deuxieme operateur present.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-018', 'securite', 'published', true, 'Lors d une mise a disposition, que faut-il faire des scelles poses ?', '["Les remplacer par une consigne orale","Les laisser sans identification","Les poser, les suivre et verifier leur situation avant la suite des travaux","Les retirer immediatement apres la pose"]'::jsonb, 2, 'Le suivi des scelles fait partie de la mission de mise a disposition.', 'DRH-DEF-LPU-037', '["operateur"]'::jsonb),
('NC-OP-019', 'securite', 'published', false, 'Quelle information rend un signalement terrain exploitable ?', '["Une photo sans date ni contexte","L equipement concerne, le constat, le moment et la consequence potentielle","Uniquement le mot anomalie","Le nom de la releve sans le lieu"]'::jsonb, 1, 'Le signalement doit permettre le diagnostic et la tracabilite, conformement a la methode FAF.', 'FAF-REF-004', '["operateur"]'::jsonb),
('NC-OP-020', 'securite', 'published', true, 'Face a une situation dangereuse non prevue par la fiche de ronde, que faut-il privilegier ?', '["La mise en securite, l alerte du chef de quart et la verification de la consigne applicable","Une improvisation rapide","Le retour en salle sans transmission","La poursuite de la ronde a tout prix"]'::jsonb, 0, 'La documentation FAF demande de ne jamais supposer et de verifier la procedure officielle avant de decider.', 'FAF-REF-002', '["operateur"]'::jsonb),
('NC-RD-001', 'securite', 'published', false, 'Quel est le but principal d une ronde technique ?', '["Remplacer les alarmes de la salle de controle","Autoriser seul les travaux","Changer les seuils de securite","Comparer l etat observe aux conditions attendues et faire remonter les ecarts"]'::jsonb, 3, 'Le rondier observe, releve et signale ; il ne remplace pas la chaine de conduite.', 'FAF-REF-006', '["rondier"]'::jsonb),
('NC-RD-002', 'securite', 'published', false, 'Comment un relevé de ronde doit-il etre utilise ?', '["Comme une autorisation de manœuvre","Comme un remplacement du permis de travail","Comme une trace datee permettant de suivre une tendance et un ecart","Comme une valeur isolee sans comparaison"]'::jsonb, 2, 'La tracabilite des valeurs et leur comparaison dans le temps facilitent le diagnostic.', 'FAF-REF-004', '["rondier"]'::jsonb),
('NC-RD-003', 'gaz', 'published', true, 'Sur le F213, quelle alarme de temperature doit attirer l attention lors d une ronde ?', '["Une alarme a 290 T/J","TIAL70 a 20 °C","Une alarme a 100 °C uniquement","Aucune alarme de temperature"]'::jsonb, 1, 'EXP-U-15-006 cite TIAL70 a 20 °C et une temperature normale autour de 35 °C.', 'EXP-U-15-006', '["rondier"]'::jsonb),
('NC-RD-004', 'gaz', 'published', false, 'Lors d une baisse de temperature du F213, quel controle local est prevu ?', '["Verifier le niveau local LAH213A/B et la presence de condensats","Verifier uniquement la consommation electrique","Acquitter l alarme sans sortir","Fermer la salle de controle"]'::jsonb, 0, 'Le niveau local du ballon et les condensats font partie des controles terrain mentionnes.', 'EXP-U-15-006', '["rondier"]'::jsonb),
('NC-RD-005', 'gaz', 'published', true, 'Quel risque cherche-t-on notamment a prevenir avec le F213 ?', '["La perte du signal radio","Le depassement du quota d eau potable","La panne du laboratoire","L arrivee de liquide aux bruleurs et l endommagement des chaudieres ou surchauffeurs"]'::jsonb, 3, 'Le ballon sert a recuperer les condensats pour proteger l aval du process.', 'EXP-U-15-006', '["rondier"]'::jsonb),
('NC-RD-006', 'gaz', 'published', true, 'Une purge du F213 est envisagee. Quelle verification ne doit pas etre omise ?', '["Le nombre de personnes en salle de reunion","Le niveau du chateau d eau uniquement","L isolement des vannes d encadrement avant le lancement de la purge","La couleur de la carrosserie"]'::jsonb, 2, 'La consigne impose cette verification avant une purge sous ARI.', 'EXP-U-15-006', '["rondier"]'::jsonb),
('NC-RD-007', 'torche', 'published', false, 'Sur le F113, que faut-il rechercher pendant la ronde ?', '["Le niveau des batteries du RDE","La presence de condensats et les conditions de fonctionnement associees","Uniquement la temperature exterieure","La puissance reactive"]'::jsonb, 1, 'La reprise de gaz acetyléniques impose de surveiller le niveau du F113 et de le purger en cas de condensats.', 'EXP-U-15-006', '["rondier"]'::jsonb),
('NC-RD-008', 'gaz', 'published', false, 'A quoi sert la ronde sur les zones de chauffe et de combustibles ?', '["Detecter fuites, niveaux, vibrations, echauffements et autres ecarts visibles","Valider une modification de procede","Remplacer le chef de quart","Autoriser une entreprise sans permis"]'::jsonb, 0, 'Les definitions de fonction listent ces observations comme missions de surveillance terrain.', 'DRH-DEF-LPU-021', '["rondier"]'::jsonb),
('NC-RD-009', 'hydrogene', 'published', true, 'Lors d une surveillance d un reseau H2, quelle pratique est la plus sure ?', '["Ouvrir une purge sans verifier le cadre d intervention","Neutraliser les alarmes de detection","Attendre la prochaine ronde","Suivre les parametres et purges selon la consigne en vigueur et signaler tout ecart"]'::jsonb, 3, 'La consigne d interface H2 repartit les responsabilites et impose le respect de la procedure officielle.', 'EXP-U-15-004', '["rondier"]'::jsonb),
('NC-RD-010', 'securite', 'published', true, 'Quel appareil est cite pour la detection des atmospheres dangereuses sur le secteur ?', '["Un manometre de vapeur","Un registre papier sans mesure","L explosimetre, utilise selon EXP-U-02-011","Un téléphone personnel"]'::jsonb, 2, 'La consigne EXP-U-02-011 encadre les detecteurs explosimetres de la Centrale.', 'EXP-U-02-011', '["rondier"]'::jsonb),
('NC-RD-011', 'securite', 'published', false, 'Que faire lorsqu une valeur de ronde est incoherente avec l indication salle de controle ?', '["Poursuivre sans aucune trace","Conserver les deux informations, verifier la mesure et alerter si l ecart persiste","Modifier la valeur terrain pour la faire correspondre","Jeter la feuille de releve"]'::jsonb, 1, 'Une incoherence est un signal a diagnostiquer, pas une valeur a corriger arbitrairement.', 'FAF-REF-004', '["rondier"]'::jsonb),
('NC-RD-012', 'securite', 'published', true, 'Un intervenant exterieur est present pendant une ronde. Quel controle releve du poste ?', '["Verifier qu il est autorise et equipe selon les regles applicables","L autoriser verbalement sans verifier","Lui confier la ronde","Supprimer la signalisation"]'::jsonb, 0, 'La fonction de chef de poste utilites rappelle le controle des personnes exterieures, de leur autorisation et de leurs EPI.', 'DRH-DEF-LPU-020', '["rondier"]'::jsonb),
('NC-RD-013', 'securite', 'published', false, 'Comment traiter une fuite reperee sur une ligne pendant la ronde ?', '["La boucher avec un moyen improvise","La photographier uniquement","Poursuivre sans informer pour eviter un arret","Signaler le lieu et la nature de la fuite, puis appliquer la conduite a tenir autorisee"]'::jsonb, 3, 'Le rondier ne remplace pas la procedure : il qualifie le constat et transmet pour decision.', 'FAF-REF-002', '["rondier"]'::jsonb),
('NC-RD-014', 'securite', 'published', false, 'Quel support est adapte a un ecart de maintenance detecte sur le terrain ?', '["Une modification du schema unifilaire","Une suppression de la ronde","Un avis ou le processus travaux prevu par l organisation","Un message oral sans suite"]'::jsonb, 2, 'Les definitions de fonction demandent d emettre les avis necessaires selon le processus travaux.', 'DRH-DEF-LPU-021', '["rondier"]'::jsonb),
('NC-RD-015', 'rechauffeurs', 'published', false, 'Dans une zone de chauffe, quel regroupement d indices doit etre observe ?', '["Le nom de l equipe precedente","Fuite, vibration, echauffement, niveau d huile et etat des bruleurs","Uniquement la couleur des tuyauteries","Uniquement la charge electrique"]'::jsonb, 1, 'Ces indices sont cites dans les activites de surveillance des equipements exterieurs.', 'DRH-DEF-LPU-037', '["rondier"]'::jsonb),
('NC-RD-016', 'securite', 'published', false, 'Pourquoi la proprete de la zone fait-elle partie de la ronde ?', '["Elle contribue a la securite, a la detection des fuites et a la bonne exploitation","Elle remplace les EPI","Elle permet de supprimer les relevés","Elle autorise une intervention sous tension"]'::jsonb, 0, 'La proprete et le rangement sont des elements de prevention et de surveillance des installations.', 'DRH-DEF-LPU-020', '["rondier"]'::jsonb),
('NC-RD-017', 'securite', 'published', true, 'Un detecteur donne une alarme. Quelle reaction est conforme a une demarche FAF ?', '["Acquitter sans rechercher la cause","Entrer dans la zone pour confirmer visuellement","Poursuivre la ronde comme si de rien n etait","Se mettre en securite, identifier la consigne applicable et transmettre l information"]'::jsonb, 3, 'La conduite depend de la consigne, mais la mise en securite et l alerte sont les premiers reflexes.', 'EXP-U-02-011', '["rondier"]'::jsonb),
('NC-RD-018', 'securite', 'published', false, 'Quel est le bon usage d une photographie prise pendant une ronde ?', '["Publier l image sans contexte","Modifier la procedure","Completer un signalement date et localise, sans remplacer l analyse ni la consigne","Remplacer systématiquement le cahier de quart"]'::jsonb, 2, 'Un support visuel peut aider la tracabilite, mais ne remplace jamais la procedure officielle.', 'FAF-REF-002', '["rondier"]'::jsonb),
('NC-RD-019', 'securite', 'published', true, 'Si la ronde rencontre une situation non couverte par les instructions disponibles, que faire ?', '["Effacer la question de la feuille","Ne pas improviser et demander une validation a la hierarchie ou au referent habilite","Choisir l option la plus rapide","Copier la manœuvre d une autre zone"]'::jsonb, 1, 'Les regles documentaires interdisent de supposer une procedure absente.', 'FAF-REF-002', '["rondier"]'::jsonb),
('NC-RD-020', 'securite', 'published', false, 'Quel est le livrable essentiel d une bonne ronde ?', '["Une observation exploitable : equipement, valeur ou symptome, heure, lieu et action engagee","Une liste sans heure ni lieu","Une validation de production uniquement","Une feuille vierge si aucun ecart n est vu"]'::jsonb, 0, 'Une ronde utile produit une trace permettant le suivi, le diagnostic et le retour d experience.', 'FAF-REF-004', '["rondier"]'::jsonb),
('NC-CT-001', 'rechauffeurs', 'published', true, 'Quelle est la mission centrale du chef de poste thermique ?', '["Gerer uniquement les permis electriques","Surveiller uniquement les stocks magasin","Remplacer le service HSEQ","Exploiter les installations de production pour fournir les utilites hors electricite en securite"]'::jsonb, 3, 'La definition de fonction rattache le chef de poste thermique a la conduite des installations de production d energie et d utilites hors electricite.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-002', 'securite', 'published', true, 'Lors d une situation dangereuse, quelle priorite doit guider le chef de poste thermique ?', '["Attendre l autorisation de la releve","Acquitter l alarme avant toute analyse","Mettre fin a la situation dangereuse et informer les personnes concernees","Maintenir la production a tout prix"]'::jsonb, 2, 'La definition de fonction demande de prendre les mesures necessaires et de donner priorite a la securite.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-003', 'securite', 'published', false, 'Quel rituel est attendu en debut de poste ?', '["Commencer les manœuvres sans transmission","Faire le point avec le chef de poste precedent, consulter les supports et relever les indisponibilites","Effacer les informations de la releve precedente","Modifier les limites d alarme"]'::jsonb, 1, 'La prise de poste comprend la transmission, la consultation des supports et la mise a jour des rapports.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-004', 'rechauffeurs', 'published', false, 'Que surveille le chef de poste thermique depuis son pupitre ?', '["Les parametres d exploitation et leurs derives","Uniquement les consommations administratives","Les badges des visiteurs","Les permis de fouille du site"]'::jsonb, 0, 'La conduite au pupitre doit permettre d anticiper les problemes et de maintenir la fourniture.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-005', 'rechauffeurs', 'published', true, 'A qui doit-il signaler une derive qui impacte le secteur des utilites ?', '["Uniquement au fournisseur GDF","A personne si la production continue","Au laboratoire uniquement","Au chef de poste utilites et au chef de quart selon l impact"]'::jsonb, 3, 'La definition de fonction demande d informer les responsables concernes des derives et anomalies.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-006', 'rechauffeurs', 'published', false, 'Avec quel poste la gestion des turbo-alternateurs doit-elle etre coordonnee ?', '["Le laboratoire","Le service expéditions","Le chef de poste electrique","Le magasinier"]'::jsonb, 2, 'Le document de fonction cite la concertation avec le chef de poste electrique.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-007', 'rechauffeurs', 'published', false, 'Que doit faire le chef de poste thermique vis-a-vis des operateurs lors d une manœuvre ?', '["Supprimer la communication radio","Les informer des manœuvres a effectuer et de leurs conditions","Leur laisser decouvrir la manœuvre sur le terrain","Modifier seul leur planning"]'::jsonb, 1, 'L information des operateurs fait partie des activites de conduite et de coordination.', 'DRH-DEF-LPU-018', '["chef-thermique"]'::jsonb),
('NC-CT-008', 'gaz', 'published', false, 'Quelle est la tranche garantie de consommation GDF citee dans EXP-U-15-002 ?', '["290 T/J","14,3 T/H","19 T/H","2,3 T/H"]'::jsonb, 0, 'La tranche garantie du contrat est fixee a 290 tonnes par jour.', 'EXP-U-15-002', '["chef-thermique"]'::jsonb),
('NC-CT-009', 'gaz', 'published', true, 'Quelle valeur horaire correspond a la tolerance temporaire de quatre heures ?', '["10 T/H","19 T/H","290 T/J","14,3 T/H"]'::jsonb, 3, 'La tolerance temporaire indiquee dans la consigne est de 14,3 T/H sur quatre heures.', 'EXP-U-15-002', '["chef-thermique"]'::jsonb),
('NC-CT-010', 'gaz', 'published', true, 'A quel seuil stabilise le chef de quart doit-il etre alerte pour la consommation GDF ?', '["A 290 T/J uniquement","A 35 °C","Au-dessus de 10 T/H","Au-dessus de 2,3 T/H"]'::jsonb, 2, 'La consigne indique un seuil d alerte hierarchique de 10 T/H en situation stabilisee.', 'EXP-U-15-002', '["chef-thermique"]'::jsonb),
('NC-CT-011', 'gaz', 'published', false, 'Que represente le point 6Q440 ?', '["La puissance reactive","La consommation instantanee de GDF de Naphtachimie","La temperature du F213","La consommation H2 du site"]'::jsonb, 1, 'Le point 6Q440 suit la consommation instantanee de GDF de Naphtachimie.', 'EXP-U-15-002', '["chef-thermique"]'::jsonb),
('NC-CT-012', 'gaz', 'published', true, 'Lors d une alarme de consommation, quelle trace est attendue ?', '["La valeur du pic, son explication et l appel au cahier de quart","Un acquittement sans commentaire","Une capture sans date","La suppression de l historique"]'::jsonb, 0, 'La consigne demande d informer, d expliquer le depassement et de tracer l appel au cahier de quart.', 'EXP-U-15-002', '["chef-thermique"]'::jsonb),
('NC-CT-013', 'torche', 'published', true, 'Quel est le principe general de la gestion anti-torche ?', '["Arreter toutes les protections pour reduire le debit","Agir sans validation ni trace","Attendre une perte complete de pression","Reduire les envois a la torche dans un ordre de priorite sans degrader la securite"]'::jsonb, 3, 'La consigne organise des actions graduees, reévaluees a chaque releve et encadrees par les autorisations.', 'EXP-U-15-005', '["chef-thermique"]'::jsonb),
('NC-CT-014', 'torche', 'published', false, 'Quelle verification peut etre faite avant d appeler l encadrement dans la sequence anti-torche ?', '["Arreter les turbo-alternateurs","Fermer le reseau H2","Verifier l exces d air et le mode normal des regulateurs","Changer le reglage des protections"]'::jsonb, 2, 'La verification de l exces d air et du mode normal des regulateurs est citee en premiere action.', 'EXP-U-15-005', '["chef-thermique"]'::jsonb),
('NC-CT-015', 'torche', 'published', true, 'Quelle action releve d une validation du service Programme ?', '["Lire le cahier de quart","Faire baisser les exports H2 et methane du Cracking","Ajuster l exces d air en mode normal","Verifier un niveau local"]'::jsonb, 1, 'La consigne distingue les actions immediates de celles qui necessitent l accord du service Programme.', 'EXP-U-15-005', '["chef-thermique"]'::jsonb),
('NC-CT-016', 'gaz', 'published', true, 'Pourquoi la temperature du F213 est-elle importante pour la conduite des chaudieres ?', '["Une baisse peut favoriser la condensation et l arrivee de liquide aux bruleurs","Elle determine le nombre de personnes en quart","Elle remplace le controle des explosimetres","Elle autorise automatiquement une purge"]'::jsonb, 0, 'EXP-U-15-006 relie la baisse de temperature au risque de condensation et de liquide en aval.', 'EXP-U-15-006', '["chef-thermique"]'::jsonb),
('NC-CT-017', 'gaz', 'published', false, 'Quelle pression alimente directement les surchauffeurs SI2 et SI3 depuis le reseau usine ?', '["1,3 bg","14,3 T/H","290 T/J","2,5 bg"]'::jsonb, 3, 'EXP-U-15-006 indique une alimentation directe des surchauffeurs par le reseau usine a 2,5 bg.', 'EXP-U-15-006', '["chef-thermique"]'::jsonb),
('NC-CT-018', 'gaz', 'published', true, 'Quelle precaution s applique a une purge normalement platinee du F213 ?', '["Purger vers l atmosphere sans controle","Deleguer a une personne non formee","Retirer la platine dans le cadre autorise, verifier les vannes et porter l ARI","Retirer la platine sans analyse"]'::jsonb, 2, 'La consigne renvoie a EXP-U-02-006 et encadre la purge par des controles et un ARI.', 'EXP-U-15-006', '["chef-thermique"]'::jsonb),
('NC-CT-019', 'rechauffeurs', 'published', false, 'Quel est le role des E004 et E005 dans le suivi du reseau gaz ?', '["Commander les protections HT","Rechauffer le gaz naturel et contribuer a eviter l arrivee de liquide en aval","Mesurer la consommation electrique du site","Remplacer le F113"]'::jsonb, 1, 'La consigne reseau gaz demande de verifier le bon fonctionnement des rechauffeurs en cas de baisse de temperature.', 'EXP-U-15-006', '["chef-thermique"]'::jsonb),
('NC-CT-020', 'securite', 'published', true, 'Peut-il contourner une securite pour maintenir la fourniture ?', '["Non : il applique la consigne de conduite et fait valider toute action exceptionnelle","Oui, si la charge est prioritaire","Oui, sans enregistrer l action","Oui, si l alarme est ancienne"]'::jsonb, 0, 'Les regles FAF rappellent que les procedures officielles et la securite ne sont pas contournables par improvisation.', 'FAF-REF-002', '["chef-thermique"]'::jsonb),
('NC-CE-001', 'securite', 'published', false, 'Quel perimetre couvre le RDE selon la definition de fonction ?', '["Uniquement les tableaux 400 V","Uniquement les turbo-alternateurs","Uniquement les postes des clients","Des arrivees 225/63 kV jusqu aux secondaires 5,5/3,2/400 V, cables inclus"]'::jsonb, 3, 'La definition de fonction decrit le RDE depuis les arrivées RTE jusqu a la distribution finale.', 'DRH-DEF-LPU-019', '["chef-elec"]'::jsonb),
('NC-CE-002', 'securite', 'published', true, 'Dans toutes ses actions, quel ordre de priorite est explicitement donne ?', '["Vitesse, production, tracabilite","Economie, confort, securite","Securite des personnes, securite des installations, continuite de l alimentation","Continuite, cout, production"]'::jsonb, 2, 'Cet ordre de priorite est indique dans la definition de fonction du chef de poste electrique.', 'DRH-DEF-LPU-019', '["chef-elec"]'::jsonb),
('NC-CE-003', 'securite', 'published', true, 'Avant une manœuvre programmee de reseau, quel document doit etre prepare ?', '["Un releve de consommation GDF","Une fiche de manœuvre detaillee chronologiquement","Un simple appel telephonique","Une photo du poste"]'::jsonb, 1, 'EXP-U-17-003 impose une fiche de manœuvre preparee en amont et detaillee.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-004', 'securite', 'published', false, 'Qui peut rediger la fiche de manœuvre selon EXP-U-17-003 ?', '["Le Chef de Poste Electricien ou les preparateurs/superviseurs HT/BT","Le laboratoire uniquement","Une entreprise sans verification","Un operateur non habilite"]'::jsonb, 0, 'La consigne identifie ces redacteurs et prevoit une verification par le responsable ou son delegataire.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-005', 'securite', 'published', true, 'Ou doit etre reporte le plan des mises a la terre ?', '["Dans le cahier de quart thermique uniquement","Sur une feuille sans numero","Uniquement dans un email","Sur le schema unifilaire du poste 15 kV ou 63 kV dans le registre de consignation"]'::jsonb, 3, 'EXP-U-17-003 demande un schema des positions de terres, reference dans le registre de consignation.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-006', 'securite', 'published', true, 'A quoi le registre de consignation doit-il faire reference ?', '["Aux consommations de vapeur","A la feuille de ronde H2","Aux numeros des PTE rattaches a chaque operation de consignation","Aux seuls noms des visiteurs"]'::jsonb, 2, 'La consigne impose le lien entre consignation et permis de travaux electriques.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-007', 'securite', 'published', false, 'Quelle distinction doit etre faite avant de preparer une manœuvre ?', '["Client interne ou externe uniquement","Manœuvre programmee ou non programmee","Quart de jour ou de nuit uniquement","Vapeur haute ou basse uniquement"]'::jsonb, 1, 'EXP-U-17-003 distingue explicitement ces deux familles de manœuvres.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-008', 'securite', 'published', false, 'Que doit faire le chef de poste electrique s il constate une anomalie pendant une manœuvre ?', '["La remonter a l equipe jour du Service Electrique","La masquer pour terminer la fiche","Changer le schema sans validation","Poursuivre sans aucune trace"]'::jsonb, 0, 'La consigne de preparation demande de remonter toute anomalie constatee.', 'EXP-U-17-003', '["chef-elec"]'::jsonb),
('NC-CE-009', 'securite', 'published', false, 'Quels moyens servent a surveiller le RDE depuis le poste ?', '["Le seul retour oral de la releve","La consommation GDF","Le registre des visiteurs","Les appareils de mesure et de signalisation disponibles"]'::jsonb, 3, 'La definition de fonction cite les appareils de mesure et de signalisation en salle et dans les postes.', 'DRH-DEF-LPU-019', '["chef-elec"]'::jsonb),
('NC-CE-010', 'securite', 'published', false, 'Quelle trace fait partie du cahier de quart electrique ?', '["Les resultats du laboratoire","Les commandes magasin","Incidents, manœuvres, permis, consignations et informations techniques utiles","Uniquement les pauses de l equipe"]'::jsonb, 2, 'Le cahier de quart electrique regroupe les informations d exploitation et de travaux du domaine.', 'DRH-DEF-LPU-019', '["chef-elec"]'::jsonb),
('NC-CE-011', 'securite', 'published', true, 'Quel niveau d habilitation est cite pour les manœuvres du chef de poste electrique ?', '["Une habilitation choisie apres l incident","B2V, H2V, BR, BC, HC et HE essai selon le niveau requis","Aucune habilitation","H0 uniquement pour toute manœuvre"]'::jsonb, 1, 'La definition de fonction mentionne les habilitations necessaires au domaine, a confirmer selon l operation.', 'DRH-DEF-LPU-019', '["chef-elec"]'::jsonb),
('NC-CE-012', 'securite', 'published', true, 'Lors d un incident electrique majeur, quelle information doit etre transmise rapidement ?', '["La situation a la hierarchie LPU et a la hierarchie du Service Electrique ou leurs permanences","Uniquement au laboratoire","Aucune information avant le retour de tension","Seulement au fournisseur GDF"]'::jsonb, 0, 'EXP-U-17-002 demande de prevenir les hierarchies ou permanences des que possible.', 'EXP-U-17-002', '["chef-elec"]'::jsonb),
('NC-CE-013', 'securite', 'published', true, 'En cas de disparition totale des alimentations RTE, quel objectif est prioritaire dans la conduite ?', '["Redemarrer toutes les machines sans diagnostic","Augmenter la consommation reactive","Supprimer les rondes dans les postes","Sauvegarder les reseaux prioritaires et maintenir le niveau d eau de mer"]'::jsonb, 3, 'EXP-U-17-002 identifie ces objectifs avant les autres actions.', 'EXP-U-17-002', '["chef-elec"]'::jsonb),
('NC-CE-014', 'securite', 'published', true, 'Lorsqu un turbo-alternateur ilote pour couvrir le prioritaire, quels parametres doivent etre regles apres ilotage ?', '["La temperature des lancettes","La consommation d eau potable","La frequence et la tension","Le niveau F213 et la pression H2"]'::jsonb, 2, 'La conduite d incident electrique prevoit le reglage de la frequence et de la tension apres ilotage.', 'EXP-U-17-002', '["chef-elec"]'::jsonb),
('NC-CE-015', 'securite', 'published', false, 'Apres le retour de la tension RTE et le retour au schema normal, quelle verification terrain est prevue ?', '["La modification des protections","Une ronde dans les postes pour verifier onduleurs, chargeurs et systemes normal/secours","La suppression du registre de consignation","La fermeture des communications"]'::jsonb, 1, 'EXP-U-17-002 demande une ronde des postes et la verification de ces equipements.', 'EXP-U-17-002', '["chef-elec"]'::jsonb),
('NC-CE-016', 'securite', 'published', false, 'Avant un travail BT hors tension, quel moyen verifie l absence de tension ?', '["Un VAT, et non un multimètre","Un test visuel uniquement","Le téléphone du chef de quart","La dernière valeur du pupitre"]'::jsonb, 0, 'EXP-U-28-007 distingue explicitement le VAT du multimètre pour la verification d absence de tension.', 'EXP-U-28-007', '["chef-elec"]'::jsonb),
('NC-CE-017', 'securite', 'published', true, 'Avant de sectionner un cable electrique, quelle condition documentaire est obligatoire ?', '["Un accord oral de l intervenant","Une ronde thermique uniquement","Une photo du cable","Un Permis de Travail Electrique vise par les responsables prevus"]'::jsonb, 3, 'EXP-U-28-009 interdit le sectionnement sans PTE vise par les responsables identifies.', 'EXP-U-28-009', '["chef-elec"]'::jsonb),
('NC-CE-018', 'securite', 'published', true, 'Si un cable est inconnu ou identifie avec doute, comment doit-il etre considere ?', '["Sans danger si le plan est absent","Pret a sectionner apres un appel","Potentiellement sous tension, avec une analyse de risque specifique","Hors tension par defaut"]'::jsonb, 2, 'La consigne impose de considerer le cable potentiellement sous tension et de realiser une ADR.', 'EXP-U-28-009', '["chef-elec"]'::jsonb),
('NC-CE-019', 'securite', 'published', true, 'Que doit preceder le sectionnement d un cable de puissance ?', '["La suppression de la mise a la terre","Le poinçonnement prealable avec l appareil prevu, maintenu durant le sectionnement","Une coupe directe a la pince","Une purge du reseau gaz"]'::jsonb, 1, 'EXP-U-28-009 prevoit le poinçonnement a distance avant la coupure.', 'EXP-U-28-009', '["chef-elec"]'::jsonb),
('NC-CE-020', 'securite', 'published', true, 'En cas d incendie dans un local electrique, quelle reference doit guider l action ?', '["EXP-U-17-004 et la conduite officielle du site","Une improvisation de l operateur","La procedure anti-torche","La consigne de consommation GDF"]'::jsonb, 0, 'La reponse doit s appuyer sur la consigne incendie electrique et la chaine d alerte, pas sur une improvisation.', 'EXP-U-17-004', '["chef-elec"]'::jsonb),
('NC-CQ-001', 'securite', 'published', true, 'Quelle est la priorite generale d une decision de chef de quart ?', '["La production avant la securite","La rapidite avant la tracabilite","Le maintien du plan initial quoi qu il arrive","La securite des personnes et des installations avant la production"]'::jsonb, 3, 'La charte FAF et les definitions de fonction placent la securite au premier rang.', 'FAF-REF-001', '["chef-quart"]'::jsonb),
('NC-CQ-002', 'gaz', 'published', true, 'Qui dispose de la vision globale et de l autorite sur le quota de gaz naturel ?', '["Le laboratoire","Le fournisseur H2","Le Chef de Quart de la Centrale Sud","Le chef de poste electrique seul"]'::jsonb, 2, 'EXP-U-15-002 attribue cette vision et cette autorite au Chef de Quart de la Centrale Sud.', 'EXP-U-15-002', '["chef-quart"]'::jsonb),
('NC-CQ-003', 'securite', 'published', false, 'Quelle information doit accompagner une decision prise pendant un incident ?', '["Le nom de l equipe precedente","La situation observee, la priorite, l action engagee et les interlocuteurs informes","Une consigne orale non tracee","Uniquement le resultat final"]'::jsonb, 1, 'La methode FAF evalue le raisonnement, la communication et la tracabilite des decisions.', 'FAF-REF-004', '["chef-quart"]'::jsonb),
('NC-CQ-004', 'securite', 'published', true, 'Que doit faire un chef de quart face a une situation dangereuse signalee par un operateur ?', '["Prendre ou faire prendre les mesures de mise en securite et coordonner l alerte","Demander de poursuivre la ronde","Attendre la fin du poste","Modifier la procedure oralement"]'::jsonb, 0, 'Le chef de quart organise la reponse et doit mettre fin aux situations dangereuses.', 'DRH-DEF-LPU-017', '["chef-quart"]'::jsonb),
('NC-CQ-005', 'securite', 'published', false, 'Quel role joue la prise de poste dans la conduite globale ?', '["Reinitialiser toutes les alarmes","Supprimer les rapports precedents","Eviter les echanges avec l equipe","Recuperer les indisponibilites, surveillances particulieres et informations de la releve"]'::jsonb, 3, 'Les definitions de fonction associent la releve et les supports d information a une conduite sure.', 'DRH-DEF-LPU-018', '["chef-quart"]'::jsonb),
('NC-CQ-006', 'securite', 'published', true, 'Comment le chef de quart utilise-t-il un adjoint ou un renfort ?', '["En lui confiant une manœuvre hors habilitation","En supprimant la communication de quart","Selon ses competences, pour remplacer, seconder ou former sous son autorite","En lui deleguant toute decision sans supervision"]'::jsonb, 2, 'Les definitions de fonction de l adjoint et du renfort prevoient remplacement ou soutien sous supervision du chef de quart.', 'DRH-DEF-LPU-017', '["chef-quart"]'::jsonb),
('NC-CQ-007', 'securite', 'published', true, 'Que doit faire le chef de quart si une situation n est pas couverte par la documentation disponible ?', '["Inventer une limite operatoire","Suspendre l improvisation et solliciter la hierarchie ou le referent habilite","Choisir une sequence issue d un autre atelier","Poursuivre jusqu a apparition d une alarme"]'::jsonb, 1, 'FAF-REF-002 interdit d inventer une procedure, une limite ou une responsabilite.', 'FAF-REF-002', '["chef-quart"]'::jsonb),
('NC-CQ-008', 'torche', 'published', false, 'A quelle echeance les actions anti-torche sont-elles reévaluees ?', '["A chaque releve","Une fois par an","Uniquement apres une mise a la torche","Jamais apres lancement"]'::jsonb, 0, 'EXP-U-15-005 prevoit une reévaluation a chaque releve.', 'EXP-U-15-005', '["chef-quart"]'::jsonb),
('NC-CQ-009', 'torche', 'published', true, 'Quel principe doit encadrer un arbitrage anti-torche ?', '["Choisir toujours l action la plus rapide","Supprimer les protections","Cacher l evenement dans le compte rendu","Reduire les envois sans degrader la securite et avec le niveau d autorisation requis"]'::jsonb, 3, 'La reduction des emissions reste subordonnee a la securite, aux procedures et a la tracabilite.', 'EXP-U-15-005', '["chef-quart"]'::jsonb),
('NC-CQ-010', 'securite', 'published', true, 'En cas de disparition totale des alimentations RTE, quel ordre d analyse est donne par la consigne electrique ?', '["Uniquement les clients externes","Redemarrage general immediat","Prioritaire, puis eau de mer, puis les autres actions","Autres actions, puis prioritaire"]'::jsonb, 2, 'EXP-U-17-002 structure la conduite selon ces priorites.', 'EXP-U-17-002', '["chef-quart"]'::jsonb),
('NC-CQ-011', 'securite', 'published', true, 'Lors d un incident electrique majeur, quelles equipes doivent etre coordonnees ?', '["Aucune equipe avant le retour RTE","L exploitation electrique, les equipes postees et les unites impactees","Uniquement le laboratoire","Uniquement le fournisseur GDF"]'::jsonb, 1, 'La mission du chef de quart est de coordonner les ressources et les interfaces impactees.', 'EXP-U-17-002', '["chef-quart"]'::jsonb),
('NC-CQ-012', 'securite', 'published', false, 'Apres retour a une alimentation normale, que faut-il faire avant de laisser chaque unite redemarrer ?', '["Informer chaque unite de la fin de l incident et des conditions de redemarrage","Laisser chaque unite choisir seule","Supprimer le cahier de quart","Modifier les protections electriques"]'::jsonb, 0, 'EXP-U-17-002 prevoit l information des unites avant le redemarrage possible.', 'EXP-U-17-002', '["chef-quart"]'::jsonb),
('NC-CQ-013', 'securite', 'published', true, 'Quelle competence est attendue du chef de quart en situation de pression ?', '["Agir sans communiquer","Attendre une decision impossible a obtenir","Deleguer sans verifier","Prendre une decision sure, communiquer et justifier la priorisation"]'::jsonb, 3, 'Les definitions de fonction et le FAF evaluent la decision, la communication et le raisonnement.', 'DRH-DEF-LPU-017', '["chef-quart"]'::jsonb),
('NC-CQ-014', 'securite', 'published', false, 'Quel est l interet d un cahier de quart correctement renseigne ?', '["Eviter les transmissions orales","Supprimer les analyses de causes","Assurer la continuite entre equipes et la tracabilite des evenements","Remplacer toutes les procedures"]'::jsonb, 2, 'Le cahier de quart porte les evenements et soutient la transmission entre postes.', 'DRH-DEF-LPU-019', '["chef-quart"]'::jsonb),
('NC-CQ-015', 'gaz', 'published', true, 'En cas d alarme de consommation GDF, quelle action de coordination est attendue ?', '["Arreter la surveillance","Informer les interlocuteurs definis, tracer l appel et faire appliquer les actions autorisees","Acquitter et attendre","Modifier le quota du contrat"]'::jsonb, 1, 'EXP-U-15-002 articule information du CK4, traçabilite et reduction possible de la consommation.', 'EXP-U-15-002', '["chef-quart"]'::jsonb),
('NC-CQ-016', 'securite', 'published', true, 'Un depassement d une condition operatoire critique est signale. Quelle conduite est correcte ?', '["Appliquer EXP-U-02-019, securiser la situation et faire remonter l evenement","Poursuivre pour voir si la valeur revient","Supprimer l alarme","Inventer un seuil compensatoire"]'::jsonb, 0, 'La fiche de conduite doit etre appliquee et l ecart traite selon la chaine prevue.', 'EXP-U-02-019', '["chef-quart"]'::jsonb),
('NC-CQ-017', 'securite', 'published', true, 'Un by-pass d un systeme de securite peut-il etre decide informellement ?', '["Oui si la production est prioritaire","Oui pendant une seule releve","Oui si aucun incident n est visible","Non, il doit respecter EXP-U-02-025 et le processus d autorisation applicable"]'::jsonb, 3, 'Les by-pass de securite sont encadres par une consigne et une autorisation, jamais par une decision informelle.', 'EXP-U-02-025', '["chef-quart"]'::jsonb),
('NC-CQ-018', 'securite', 'published', false, 'Comment un chef de quart exploite-t-il un retour d experience valide ?', '["Pour supprimer les formations","Pour changer une limite sans validation","Pour renforcer les pratiques et les plans de progression sans modifier seul une procedure","Pour remplacer la procedure officielle"]'::jsonb, 2, 'FAF-REF-002 distingue le REX, la procedure officielle et le processus de revision.', 'FAF-REF-002', '["chef-quart"]'::jsonb),
('NC-CQ-019', 'securite', 'published', false, 'Quels criteres un debriefing FAF doit-il reprendre ?', '["La production sans la securite","Faits, decisions, procedures, bonnes pratiques et axes de progres","Uniquement le score","Uniquement les erreurs individuelles"]'::jsonb, 1, 'Le guide Gun Drills structure le debriefing autour des faits, decisions, procedures et progres.', 'FAF-REF-005', '["chef-quart"]'::jsonb),
('NC-CQ-020', 'securite', 'published', true, 'Quel est le role de l application par rapport aux consignes officielles ?', '["Aider a s entrainer et tracer les acquis sans remplacer la procedure ni la chaine de commandement","Remplacer les procedures par le questionnaire","Autoriser automatiquement les manœuvres","Decider a la place du chef de quart"]'::jsonb, 0, 'Le referentiel FAF rappelle que l application est un assistant pedagogique et ne remplace pas les decisions habilitees.', 'FAF-REF-008', '["chef-quart"]'::jsonb)
on conflict (id) do update set
  theme_id = excluded.theme_id,
  status = excluded.status,
  critical = excluded.critical,
  prompt = excluded.prompt,
  choices = excluded.choices,
  correct_index = excluded.correct_index,
  rationale = excluded.rationale,
  source = excluded.source,
  target_posts = excluded.target_posts,
  updated_at = now();

create index if not exists questions_target_posts_gin_idx on public.questions using gin (target_posts);

do $$
begin
  if (select count(*) from public.questions where id like 'NC-%') <> 100 then
    raise exception 'Les questionnaires par poste doivent contenir exactement 100 questions NC.';
  end if;
end $$;

commit;
